version: '3.4'

volumes:
  productdata:

networks:
  backend:
  frontend:


services:

  mysql:
    image: mysql
    volumes:
      - productdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=uali
      - bind-address=0.0.0.0
  
  dbinit:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - backend
    environment:
      - DBINIT=true
      - DBHOST:mysql
    depends_on:
      - mysql
  
  mvc:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - backend
      - frontend
    environment:
      - DBHOST:mysql
    depends_on:
      - mysql
  
  loadbalancer:
    build:
      context: ../LoadBalancer
      dockerfile: dockerfile
    ports:
      - 3000:80
    networks:
      - frontend