version: '3.4'

services:
  mate:
    image: mate
    container_name: mate
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=uali
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8001:443"
      - "8000:80"
    volumes:
      - ~\.aspnet\https:/https/